### ISSUE TITLE
/url/to/ not route to To.get_all after secure

### ISSUE THREAD

**Issue by missuor** [pecan/pecan#106]
ref:pecan.secure._SecuredAttribute._lookup

    @_secure_method('_check_permissions')
    @expose()
    def _lookup(self, *remainder):
        return self.obj, remainder # <=== Here !

ref: pecan.rest:RestController._handle_get

    def _handle_get(self, method, remainder, request=None):
        '''
        Routes ``GET`` actions to the appropriate controller.
        '''
        if request is None:
            self._raise_method_deprecation_warning(self._handle_get)

        # route to a get_all or get if no additional parts are available
        if not remainder or remainder == ['']: # <=== Here! ( ('',) is not equal to [''] and controller goes to be a `get_one`
example:

/some/urls/to/controller ==> Controller.get_all
/some/urls/to/controller/ ==> Controller.get_one
urls above should route to Controller.get_all

PR: https://github.com/pecan/pecan/pull/105

**Comment by cleverdevil** [comment]
Fix has merged. Thanks for the report and the PR!
