### ISSUE TITLE
Deprecation warning due to invalid escape sequences.

### ISSUE THREAD

**Issue by tirkarthi** [pecan/pecan#115]
Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this. Check https://github.com/asottile/pyupgrade/ for automatic fix of this.

```
find . -iname '*.py' | grep -Ev 'setup|rdf4|tool' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./pecan/core.py:331: DeprecationWarning: invalid escape sequence \*
  '''
./pecan/middleware/debug.py:24: DeprecationWarning: invalid escape sequence \g
  yield self.body_re.sub(b('\g<1>%s' % __CONFIG_HELP__), part)
./pecan/routing.py:49: DeprecationWarning: invalid escape sequence \(
  '^[0-9a-zA-Z-_$\(\)\.~!,;:*+@=]+$', route
```

**Comment by kajinamit** [comment]
@ryanpetrello Hi. First of all, thanks for working in this nice project :-)

I'm wondering if you mind creating a new release with the fix for this ? This is cosmetic but getting rid of multiple warning messages is still nice.

**Comment by ryanpetrello** [comment]
Hey @kajinamit,

This is the only unreleased changed for `pecan` since 1.5.1, and it's a tweak to a docstring.  This one will get picked up the next time I do a release with either a bugfix or feature.
