### ISSUE TITLE
latest gunicorn breaks pecan

### ISSUE THREAD

**Issue by dmick** [pecan/pecan#137]
See https://github.com/benoitc/gunicorn/issues/2741; I believe it's gunicorn's issue, but it causes gunicorn_pecan to break.  My current plan for our pecan application is to pin gunicorn to < 20.1.0.

**Comment by x-7** [comment]
@dmick 
i bypass the bug by command： "gunicorn wsgi:app"
but i dont know  if there are another problems with this

**Comment by ryanpetrello** [comment]
Hey @dmick,

Long time no see.

Did you ever find a resolution to this?

**Comment by dmick** [comment]
@ryanpetrello I lost any context I had about this long ago <grimace>.  I think we still have the gunicorn pin in place (looks)

**Comment by ryanpetrello** [comment]
👍 thanks @dmick.  It also looks like a bug/breaking change in the gunicorn source, and it sounds like you've got a workaround, so I'll probably go ahead and close this.
