### ISSUE TITLE
Whether to consider releasing a wheel

### ISSUE THREAD

**Issue by tklltkioc** [pecan/pecan#138]
There’s a [PEP](https://peps.python.org/pep-0491/) to release a wheel.

Advantages of wheels
1.Faster installation for pure Python packages.
2.Avoids arbitrary code execution for installation. (Avoids setup.py)
3.Allows better caching for testing and continuous integration.
4.More consistent installs across platforms and machines.

Note that https://pythonwheels.com/.
This site shows the top 360 most-downloaded packages on [PyPI](https://pypi.org/) showing which have been uploaded as wheel archives.

**Comment by ryanpetrello** [comment]
https://pypi.org/project/pecan/1.5.0/#files
