### ISSUE TITLE
`IndexError` from `get_args` in Python 2.6

### ISSUE THREAD

**Issue by alfredodeza** [pecan/pecan#15]
I am not entirely sure I understand, but trying to get a release of pecan-notario (a validation engine and decorator) and having some issues with Python 2.6, where failures look like:

    py.test -x
    ========================================================================== test session starts ===============================================================================
    platform darwin -- Python 2.6.8 -- py-1.4.30 -- pytest-2.7.2
    rootdir: /Users/alfredo/python/pecan-notario, inifile:
    collected 21 items
    
    tests/functional/test_decorator.py ............F
    
    ================================================================================ FAILURES ====================================================================================
    ______________________________________________________________ TestCallableHandler.test_basic_functionality __________________________________________________________________
    
    self = <test_decorator.TestCallableHandler object at 0x102e8f9d0>
    
        def test_basic_functionality(self):
            body = '{"key":"value"}'
            response = self.app.post('/', body,
    >           [('Content-Type', 'application/json')]
            )
    
    tests/functional/test_decorator.py:28:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    ../.tox/py26/lib/python2.6/site-packages/webtest/app.py:370: in post
        content_type=content_type)
    ../.tox/py26/lib/python2.6/site-packages/webtest/app.py:735: in _gen_request
        expect_errors=expect_errors)
    ../.tox/py26/lib/python2.6/site-packages/webtest/app.py:605: in do_request
        res = req.get_response(app, catch_exc_info=True)
    ../.tox/py26/lib/python2.6/site-packages/webob/request.py:1313: in send
        application, catch_exc_info=True)
    ../.tox/py26/lib/python2.6/site-packages/webob/request.py:1281: in call_application
        app_iter = application(self.environ, start_response)
    ../.tox/py26/lib/python2.6/site-packages/webtest/lint.py:198: in lint_app
        iterator = application(environ, start_response_wrapper)
    ../.tox/py26/lib/python2.6/site-packages/pecan/middleware/recursive.py:56: in __call__
        return self.application(environ, start_response)
    ../.tox/py26/lib/python2.6/site-packages/pecan/core.py:829: in __call__
        return super(Pecan, self).__call__(environ, start_response)
    ../.tox/py26/lib/python2.6/site-packages/pecan/core.py:677: in __call__
        controller, args, kwargs = self.find_controller(state)
    ../.tox/py26/lib/python2.6/site-packages/pecan/core.py:847: in find_controller
        controller, args, kw = super(Pecan, self).find_controller(_state)
    ../.tox/py26/lib/python2.6/site-packages/pecan/core.py:543: in find_controller
        im_self
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    self = <pecan.core.Pecan object at 0x102e8fed0>, state = <pecan.core.RoutingState object at 0x102e95110>, all_params = {'key': 'value'}, remainder = []
    argspec = ArgSpec(args=[], varargs=None, keywords=None, defaults=None), im_self = None
    
        def get_args(self, state, all_params, remainder, argspec, im_self):
            '''
                Determines the arguments for a controller based upon parameters
                passed the argument specification for the controller.
                '''
            args = []
            varargs = []
            kwargs = dict()
            valid_args = argspec.args[:]
            if ismethod(state.controller) or im_self:
    >           valid_args.pop(0)  # pop off `self`
    E           IndexError: pop from empty list
    
    ../.tox/py26/lib/python2.6/site-packages/pecan/core.py:361: IndexError

If I go and step through this part of the code, I see that `args` is an empty list, so the `pop()` fails.

I don't know why is this the case or why this is happening on Python 2.6 alone.

Investigating further, I find that if the validation decorator uses a `lambda` it all breaks. If I remove the lambda the test works.

This is how that test class looks:

    def make_app(self, schema=('key', 'value')):
        import pecan_notario
        from pecan import Pecan, expose, request
        from pecan.middleware.recursive import RecursiveMiddleware
        from webtest import TestApp

        simple_schema = schema

        class RootControllerTwo(object):
            @expose('json')
            @pecan_notario.validate(
                simple_schema, handler=lambda: '/error'
            )
            def index(self, **kw):
                return dict(success=True)

            @expose('json')
            def error(self, **kw):
                return dict(success=False, error=str(request.validation_error))

        return TestApp(RecursiveMiddleware(Pecan(RootControllerTwo())))

These might look a bit to dense, but the bottom line is that `pop()` and that this only happens when the decorator is using `lambda`.

**Comment by alfredodeza** [comment]
Managed to get a vanilla Pecan blow up. This is the root controller (adds only the decorator that accepts the `lambda`):

    from pecan import expose, redirect
    from webob.exc import status_map
    
    
    def example(handler):
        def deco(f):
            def wrapped(*args, **kwargs):
                if callable(handler):
                    handler()
                return f(*args, **kwargs)
            return wrapped
        return deco
    
    
    class RootController(object):
    
        @expose(generic=True, template='index.html')
        @example(lambda: True)
        def index(self):
            return dict()
    
        @index.when(method='POST')
        def index_post(self, q):
            redirect('http://pecan.readthedocs.org/en/latest/search.html?q=%s' % q)
    
        @expose('error.html')
        def error(self, status):
            try:
                status = int(status)
            except ValueError:  # pragma: no cover
                status = 500
            message = getattr(status_map.get(status), 'explanation', '')
            return dict(status=status, message=message)
Which fails running the vanilla tests. On:

    def test_get(self):
        response = self.app.get('/')

The traceback is the same:

    self = <pecan.core.Pecan object at 0x109068390>, state = <pecan.core.RoutingState object at 0x10917fd90>, all_params = {}, remainder = []
    argspec = ArgSpec(args=[], varargs=None, keywords=None, defaults=None), im_self = <deco.controllers.root.RootController object at 0x10917f6d0>
    
        def get_args(self, state, all_params, remainder, argspec, im_self):
            '''
                Determines the arguments for a controller based upon parameters
                passed the argument specification for the controller.
                '''
            args = []
            varargs = []
            kwargs = dict()
            valid_args = argspec.args[:]
            if ismethod(state.controller) or im_self:
    >           valid_args.pop(0)  # pop off `self`
    E           IndexError: pop from empty list
    
    ../.tox/py26/lib/python2.6/site-packages/pecan/core.py:361: IndexError

I managed to add an `if` condition to call `pop()` only if `valid_args` has something in it and all worked correctly. If this is an acceptable solution, I don't mind sending in a pull request with a test case(s)

**Comment by ryanpetrello** [comment]
Resolved via #16
