### ISSUE TITLE
1.5.0: Missing https://github.com/pecan/pecan/releases/tag/1.5.0

### ISSUE THREAD

**Issue by hswong3i** [pecan/pecan#151]
We don't have GIT tag https://github.com/pecan/pecan/releases/tag/1.5.0, yet ;-)

**Comment by a16bitsysop** [comment]
its missing this commit as well:
https://github.com/pecan/pecan/commit/22553b4e5f6a79e588e41ec00392d58d6331bba1

**Comment by ryanpetrello** [comment]
https://github.com/pecan/pecan/releases/tag/1.5.0
https://github.com/pecan/pecan/releases/tag/1.5.1
https://github.com/pecan/pecan/commit/fbd720c7cc7f035bb4436ffea869d7d7d8a09792
