### ISSUE TITLE
Online Documentation using deprecating commands 

### ISSUE THREAD

**Issue by sambhavnoobcoder** [pecan/pecan#153]
the online version of the documentation available at https://pecan.readthedocs.io/en/latest/quick_start.html#running-the-application uses the  ```python setup.py test -q``` command to initiate the tests . however this version is going to deprecate soon and using ```tox``` is recommended . Hence the online documentation needs a change , either adding the warning with the new testing commands or replacing the old one altogether . 

I would love to see the @moderators  take on this issue and if they agree , I would contribute to it myself

**Comment by markmcclain** [comment]
Thanks for creating this issue. Pull requests are always welcomed ... especially documentation updates!

**Comment by sambhavnoobcoder** [comment]
hey @markmcclain , I've made the necessary changes in  #154 . kindly look into the pr and merge if it meets requirements . I'm open to any other suggestions as well . Thanks .
