### ISSUE TITLE
Python 3-specific bug: Attribute error: 'im_class'

### ISSUE THREAD

**Issue by nmakhotkin** [pecan/pecan#19]
From OpenStack maillist thread - http://lists.openstack.org/pipermail/openstack-dev/2015-October/076022.html

Traceback: http://paste.openstack.org/show/475041/

The error goes from walk_controller method in pecan/hooks.py:

https://github.com/pecan/pecan/blob/master/pecan/hooks.py#L51

**value.im_class** should be replaced on **value.__self__.__class__**

**Comment by ryanpetrello** [comment]
Fixed in https://pypi.python.org/pypi/pecan/1.0.3

**Comment by ryanpetrello** [comment]
Released in https://pypi.python.org/pypi/pecan/1.0.3
