### ISSUE TITLE
automatic extention detection overrides explicit `content_type`

### ISSUE THREAD

**Issue by alfredodeza** [pecan/pecan#26]
I kept getting a `404 Not Found` error where I was sure I had the right code path to get to an `index` controller method using a url that ended on `.rpm`.

This happened only on a Linux box where the `mimetpye.guess_type` function guessed that something ending on `.rpm` should be a `application/x-redhat-package-manager` type. In OSX this detection doesn't return a specific content type and all tests would pass.

After enabling DEBUG logging for Pecan the error showed:

```
[ERROR   ] [pecan.core][MainThread] Controller 'index' defined does not support content_type 'application/x-redhat-package-manager'. Supported type(s): ['application/json']
```

The code to replicate the issue ( controllers/root.py ):

```
from pecan import expose, redirect
from webob.exc import status_map


class BinaryController(object):

    def __init__(self, name):
        self.name = name

    @expose('json', content_type='application/json')
    def index(self):
        return {}


class RootController(object):

    @expose(generic=True, template='index.html')
    def index(self):
        return dict()

    @index.when(method='POST')
    def index_post(self, q):
        redirect('http://pecan.readthedocs.org/en/latest/search.html?q=%s' % q)

    @expose('error.html')
    def error(self, status):
        try:
            status = int(status)
        except ValueError:  # pragma: no cover
            status = 500
        message = getattr(status_map.get(status), 'explanation', '')
        return dict(status=status, message=message)

    @expose()
    def _lookup(self, name, *remainder):
        return BinaryController(name), remainder
```

And hit `localhost:8080/some_binary.rpm`

A few things that should be noted here:
- If this is an error condition, why is it returning a 404? I was expecting a more explicit error (like a `406 Not Acceptable` which is actually used to report the same error condition a few lines above the one I was getting: https://github.com/pecan/pecan/blob/master/pecan/core.py#L506
- Automatic content-type is nice, but when it fails it should be very clear what is going on and why. It would be nice to have logging enabled for `pecan` at the error level by default (scaffolds would need to change)
- if the controller method is _explicitly_ setting the `content_type` (as shown in the example) no automatic detection should forcefully override it. The explicit content_type should be respected if present, otherwise fall back to auto detection.

**Comment by ryanpetrello** [comment]
@alfredodeza I believe this issue was resolved via #27 

I'm curious to see if you all still need the change you applied in https://github.com/ceph/shaman/pull/32
