### ISSUE TITLE
@secure decorator call target 3 times.

### ISSUE THREAD

**Issue by cluries** [pecan/pecan#38]
In this code, call 3 times  `check_permissions` in one request.

```
class RootController(object):
    @classmethod
    def check_permissions(cls):
        if user_is_admin():
            return True
        return False

    @secure('check_permissions')
    @expose()
    def topsecret(self):
        return dict()
```

**Comment by ryanpetrello** [comment]
I'm unable to reproduce this using ``pecan serve <config>``.

```python
    import logging
    from pecan import expose, secure, request

    class RootController(object):
        @classmethod
        def check_permissions(cls):
            print "check_permissions called!"
            if 'admin' in request.GET:
                return True
            return False

    @secure.secure('check_permissions')
    @expose()
    def topsecret(self):
        return dict()
```

When I use curl to test a request, e.g.,

    $ curl "localhost:8080/topsecret/?admin=True"

..."check_permissions_called" is only printed once in the server output.  I've also stuck in a ``pdb.set_trace()`` just to be sure.

1.  What version of Python and pecan are you using?
2.  Are you running this using some type of WSGI server (e.g., mod_wsgi + Apache, uwsgi, gunicorn)?
3.  What tool are you using to generate your "one request"?

**Comment by cluries** [comment]
I am sorry, i found maybe it's my problem.
I use `RestController`, when i  override `_route` , check_permissions will call more than once per request.
call times === override `_route` numbers.
```
class RootController(RestController):
    _versions = ['v1']
    _default_version = 'v1'

    v1 = v1.Controller()
 
    @expose()
    def _route(self, args, request):
        if args[0] and args[0] not in self._versions:
            args = [self._default_version] + args
        return super(RootController, self)._route(args)
```

v1.Controller
```
class Controller(RestController):
     
    person = PersonController()

    @expose()
    def _route(self, args, request):
        """ check version """
        # check version code

        return super(Controller, self)._route(args)

def authenticated():
    print "authenticated."
    return True


class PersonController(RestController):
    @secure(authenticated)
    def get_one(self, id):
        person = Person.load(id)
        return person
```

**Comment by ryanpetrello** [comment]
Your example doesn't work for me at all :/ (when I attempt to reach ``/v1/person/123``, I just get an ``HTTP 405``)  What version of pecan are you using?  Also, a few things I noticed:

Is there a reason why your ``v1.Controller`` is a ``RestController``?  You don't seem to actually be using any of the ``RestController`` functionality in that class.

Is there a reason why you're subclassing ``v1.Controller._route``?  It doesn't seem to be doing anything special.

Here's an example that should do what you need (that doesn't use ``RestController`` *or* ``_route``)::

```python
    from pecan import expose, abort
    from pecan.secure import secure

    def authenticated():
        print "authenticated."
        return True


    class PersonController(object):

        def __init__(self, id_):
            self.id_ = id_

        @secure(authenticated)
        @expose()
        def index(self):
            return self.id_


    class V1Controller(object):

        @expose()
        def _lookup(self, id_, *remainder):
            return PersonController(id_), remainder


    class RootController(object):
        _versions = ['v1']
        _default_version = 'v1'

        v1 = V1Controller()

        @expose()
        def _lookup(self, args, *remainder):
            if args[0] and args[0] not in self._versions:
                return getattr(self, self._default_version), remainder
            abort(404)
```

**Comment by cluries** [comment]
Hi, i use pecan 1.0.3 and python 2.7.11  

thanks  for your notice.

In my example,I remove some code to make it simple, `v1.Controller ` is a RestController because it's has `get` method.

subclassing  `v1.Controller._route` because i modify response and some other things. I don't use `hook` in here.

I will refactor my code, thanks very much.
