### ISSUE TITLE
expose and when decorators can't decorate non-function object decorators

### ISSUE THREAD

**Issue by kevinbenton** [pecan/pecan#47]
If a decorator is used on a controller method that is just a normal object with a __call__ method, it will not necessarily have the __code__ attribute this line[1] is looking for so pecan will fail to load when using one of these style decorators. For an example of this type of decorator, check out the oslo DB wrap db retry decorator: https://github.com/malor/oslo.db/blob/b50609bc0e63704947c0e9d66e503155e885bc0d/oslo/db/api.py#L42

1. https://github.com/pecan/pecan/blob/ce728f48787489f8cfbac96f8224d3c63a9b4490/pecan/util.py#L43

**Comment by ryanpetrello** [comment]
Closed via #49
