### ISSUE TITLE
expose(template='json',..) is magic, undocumented

### ISSUE THREAD

**Issue by dmick** [pecan/pecan#51]
Something should document the magic behavior of using 'json' as the 'template' argument to expose().

**Comment by ryanpetrello** [comment]
This is documented at https://pecan.readthedocs.org/en/latest/templates.html#the-json-renderer, but I'll expand the method's actual doctoring a bit to clarify:

https://pecan.readthedocs.org/en/latest/pecan_decorators.html?highlight=expose#pecan.decorators.expose
