### ISSUE TITLE
'json' renderer forces response body to be non-empty

### ISSUE THREAD

**Issue by alfredodeza** [pecan/pecan#72]
The following test case fails:

    class TestJsonRendering(PecanTestCase):
    
        def test_no_body_json(self):
    
            class RootController(object):
                @expose('json')
                def index(self):
                    pass
    
            app = TestApp(Pecan(RootController()))
    
            r = app.get('/')
            assert r.status_int == 204
            assert r.body == ''

The actual `r.status_int` is 200, and the body is `null`.

There is no way to force a response to have an empty body when using the `json` renderer because it treats both the implicit (with no return) and explicit (returning an actual `None`) as valid input to render a `json` response.

In `pecan.core` it sees that there is an actual body in the response so it doesn't force the `204`.

I don't know in what situations one would want to render a `None` to `null`, but I did had a valid use case where the controller might return `json` or no body at all, in which I was expecting a `204`.

This might be a documentation fix and maybe some debug messages to alert of this.

**Comment by ryanpetrello** [comment]
My opinion is that this is actually a bug, and that a controller that returns `None` with an `@expose('json')` should be an HTTP 204 (as your test case suggests).

**Comment by alfredodeza** [comment]
@ryanpetrello but you can't know for sure if the controller actually returned a `None` or if it just didn't return anything (which also, implicitly will get a `None`).

This for example is just plain impossible with the other renderers (e.g. with mako) because returning `None` (or nothing at all) would create a templating error *even* if the template has no variables to use.

**Comment by ryanpetrello** [comment]
This change seems to break a handful of OpenStack project tests that rely on the prior behavior (they're asserting that the response status is `200 OK`).

**Comment by ryanpetrello** [comment]
@alfredodeza I don't think it *matters* if the `None` is explicitly returned.  Currently if you implicitly return `None`, the JSON version just renders `null` (which I'd say is incorrect), and any template decorated controller throws a cryptic type-related error

**Comment by ryanpetrello** [comment]
I guess what I'm arguing for is this: if you have a controller that returns `None`, pecan should make the response an `204 No Content`.

**Comment by alfredodeza** [comment]
I am OK with that. It doesn't help the render to `null` which makes it valid. But if no other renderer allows for this, I vote +1 on normalization of the behavior.

**Comment by cleverdevil** [comment]
`204 No Content` is pretty clearly intended for this purpose, so I agree with @ryanpetrello.

https://httpstatuses.com/204 states the reason for this status code is:

> The server has successfully fulfilled the request and that there is no additional content to send in the response payload body.

The request is successful, and the body contains no content. Any project that is checking explicitly for a `200 OK` here is relying on a bug in our implementation, and should instead be checking that the response is, in fact, successful (e.g. the response status is in the 2XX-series).

**Comment by alfredodeza** [comment]
I agree with you both :) 

*However* it is entirely possible that a controller method implementation wants to return a `None` and *wants* to have it rendered as `null` in the body.

**Comment by ryanpetrello** [comment]
https://github.com/pecan/pecan/pull/79
