### ISSUE TITLE
RestController failed if dashes in _custom_actions

### ISSUE THREAD

**Issue by luoyancn** [pecan/pecan#74]
For my case, i need to build route path like 
/node/power-on

```
class NodeController(rest.RestController):
    @expose(route='power-on')
    def power_on(self, power_request):
        print power_request

```
Then, i got the error like follows:

`ValueError: Path segments cannot be used in combination with pecan.rest.RestController.  Remove the `route` argument to @pecan.expose on lightrest.controllers.advanced.NodeController.power_operate`

So, i modified my code like follows:

```
class NodeController(rest.RestController):
    _custom_actions = {
        'power-on': ['POST'],
    }
    @expose()
    def power_on(self, power_request):
        print power_request
```

while, i still cannot visit the url /node/power-on that i got 404 not found error.

**Comment by ryanpetrello** [comment]
A few things to note:

* If you want to specify an additional positional argument (``power_request``) with ``RestController``, you'll need to use ``HTTP PUT``.
* What you're trying to do here isn't really supported by ``RestController``.  Despite that, if it's really what you want, the following code might accomplish it:

    from pecan import expose, rest
    import six


    class NodeController(rest.RestController):
        _custom_actions = {
            'power-on': ['PUT'],
        }

        def power_on(self, power_state):
            return power_state

    setattr(
        NodeController,
        'power-on',
        expose()(six.get_method_function(NodeController.power_on))
    )

**Comment by luoyancn** [comment]
@ryanpetrello ,
Thanks for your advice.
